// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TibiaHuntMaster.Infrastructure.Data;

#nullable disable

namespace TibiaHuntMaster.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Character.CharacterDepotSaleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RealizedValue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SoldAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "SoldAtUtc");

                    b.ToTable("CharacterDepotSales", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Character.CharacterGoalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ManualProgressOffset")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartValue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TargetValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterGoals", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Character.HuntGoalConnectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterGoalId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HuntSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinisher")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamHuntSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterGoalId");

                    b.HasIndex("HuntSessionId");

                    b.HasIndex("TeamHuntSessionId");

                    b.ToTable("HuntGoalConnections", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abilities")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Armor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Article")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AttackType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Behaviour")
                        .HasColumnType("TEXT");

                    b.Property<string>("BestiaryClass")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BestiaryDifficulty")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BestiaryOccurrence")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BosstiaryCategory")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConvinceMana")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatureClass")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("History")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Illusionable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImplementedVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBoosted")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBoss")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxDmg")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Mitigation")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ParaImmune")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plural")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrimaryAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryImageFileName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryImageMimeType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryImageStorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PushObjects")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Pushable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RaceId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RunsAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondaryType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("SenseInvis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SourceLastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpawnType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strategy")
                        .HasColumnType("TEXT");

                    b.Property<string>("StructuredDataJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SummonMana")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsedElements")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("UsesSpells")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WalksAround")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WalksThrough")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentId")
                        .IsUnique();

                    b.ToTable("Creatures");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureLootEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmountRaw")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Chance")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rarity")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Raw")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId");

                    b.ToTable("CreatureLoots");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureMonsterImageLinkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchedBySlug")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("MonsterImageAssetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId")
                        .IsUnique();

                    b.HasIndex("MonsterImageAssetId");

                    b.ToTable("CreatureMonsterImageLinks");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureSoundEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId");

                    b.ToTable("CreatureSounds");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.HuntingPlaceCreatureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatureName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("HuntingPlaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId");

                    b.HasIndex("HuntingPlaceId");

                    b.ToTable("HuntingPlaceCreatures");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.HuntingPlaceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BestLoot")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BestLoot2")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BestLoot3")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BestLoot4")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BestLoot5")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoriesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreaturesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefenseKnights")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefenseMages")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefensePaladins")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExperienceStar")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImplementedVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LevelKnights")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LevelMages")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LevelPaladins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("LootStar")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LootValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Map")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Map2")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Map2Width")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Map3")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Map4")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MapWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlainTextContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawWikiText")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SkillKnights")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SkillMages")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SkillPaladins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SourceLastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StructuredDataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vocation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WikiUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentId")
                        .IsUnique();

                    b.ToTable("HuntingPlaces");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.HuntingPlaceLevelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefenseKnights")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefenseMages")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefensePaladins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HuntingPlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LevelKnights")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LevelMages")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LevelPaladins")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SkillKnights")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SkillMages")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SkillPaladins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HuntingPlaceId");

                    b.ToTable("HuntingPlaceLevels");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.ItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Armor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attrib")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategorySlug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageRange")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeathAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefenseMod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DroppedByCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EarthAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ElementAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EnergyAttack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtrasJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FireAttack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hands")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HolyAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IceAttack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImbueSlots")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Implemented")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemIdPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemIdsCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LevelRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Marketable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("NpcPrice")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NpcValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectClass")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Pickupable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plural")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrimaryAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryImageFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryImageMimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryImageStorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResistSummary")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SellTo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoundsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SourceLastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Stackable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpgradeClass")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Usable")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VocRequired")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Walkable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WeightOz")
                        .HasColumnType("TEXT");

                    b.Property<string>("WikiUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentId")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.MonsterImageAliasEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonsterImageAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonsterImageAssetId");

                    b.ToTable("MonsterImageAliases");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.MonsterImageAssetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetUri")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalSlug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RemoteAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MonsterImageAssets");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.MonsterSpawnCoordinateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Z")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MonsterSpawnCoordinates");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.MonsterSpawnCreatureLinkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreatureId")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonsterName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("MonsterSpawnCoordinateId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId");

                    b.HasIndex("MonsterSpawnCoordinateId");

                    b.ToTable("MonsterSpawnCreatureLinks");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterGoalId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HuntGroups", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntLootEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountKept")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HuntSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HuntSessionId");

                    b.ToTable("HuntLootEntries", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntMonsterEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HuntSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonsterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HuntSessionId");

                    b.ToTable("HuntMonsterEntries", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntSessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomXpRatePercent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Healing")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HuntGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HuntingPlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreLootVerificationWarning")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreXpVerificationWarning")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ImportedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDoubleLoot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDoubleXp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRapidRespawn")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Loot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawInput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RawXpGain")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SessionStartTime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Supplies")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("XpBoostActiveMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("XpBoostPercent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("XpGain")
                        .HasColumnType("INTEGER");

                    b.Property<long>("XpPerHour")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("HuntGroupId");

                    b.HasIndex("HuntingPlaceId");

                    b.ToTable("HuntSessions", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntSupplyAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HuntSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HuntSessionId");

                    b.ToTable("HuntSupplyAdjustments", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.TeamHuntMemberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Healing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Loot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Supplies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamHuntSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamHuntSessionId");

                    b.ToTable("TeamHuntMembers", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.TeamHuntSessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ImportedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LootType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawInput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SessionStartTime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalBalance")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalLoot")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalSupplies")
                        .HasColumnType("INTEGER");

                    b.Property<long>("XpGain")
                        .HasColumnType("INTEGER");

                    b.Property<long>("XpPerHour")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("TeamHuntSessions", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Imbuement.CharacterActiveImbuement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImbuementProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImbuementProfileId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImbuementRecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImbuementProfileId");

                    b.HasIndex("ImbuementProfileId1");

                    b.HasIndex("ImbuementRecipeId");

                    b.ToTable("CharacterActiveImbuements", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Imbuement.ImbuementIngredientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImbuementRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImbuementRecipeId");

                    b.HasIndex("ItemId");

                    b.ToTable("ImbuementIngredients", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Imbuement.ImbuementProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseBlankScrolls")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("ImbuementProfiles", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Imbuement.ImbuementRecipeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BaseFee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImbuementRecipes", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Imbuement.UserItemPriceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("UserItemPrices", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoyaltyTitle")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterAccounts", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterAchievementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Secret")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Name")
                        .IsUnique();

                    b.ToTable("CharacterAchievements", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterBadgeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Name")
                        .IsUnique();

                    b.ToTable("CharacterBadges", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterDeathEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KillersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimeUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "TimeUtc")
                        .IsUnique();

                    b.ToTable("CharacterDeaths", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("AchievementPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastLogin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Residence")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vocation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("World")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name", "World")
                        .IsUnique();

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterHouseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Paid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "HouseId")
                        .IsUnique();

                    b.ToTable("CharacterHouses", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterSnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FetchedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "FetchedAtUtc");

                    b.ToTable("CharacterSnapshots", (string)null);
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Character.CharacterDepotSaleEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Character.CharacterGoalEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Character.HuntGoalConnectionEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Character.CharacterGoalEntity", "Goal")
                        .WithMany()
                        .HasForeignKey("CharacterGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntSessionEntity", "SoloSession")
                        .WithMany()
                        .HasForeignKey("HuntSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.TeamHuntSessionEntity", "TeamSession")
                        .WithMany()
                        .HasForeignKey("TeamHuntSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Goal");

                    b.Navigation("SoloSession");

                    b.Navigation("TeamSession");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureEntity", b =>
                {
                    b.OwnsOne("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureDamageModifiers", "Damage", b1 =>
                        {
                            b1.Property<int>("CreatureEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("DeathFactor")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DeathRaw")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("DrownFactor")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DrownRaw")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("EarthFactor")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EarthRaw")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("EnergyFactor")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EnergyRaw")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("FireFactor")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FireRaw")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("HealFactor")
                                .HasColumnType("TEXT");

                            b1.Property<string>("HealRaw")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("HolyFactor")
                                .HasColumnType("TEXT");

                            b1.Property<string>("HolyRaw")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("HpDrainFactor")
                                .HasColumnType("TEXT");

                            b1.Property<string>("HpDrainRaw")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("IceFactor")
                                .HasColumnType("TEXT");

                            b1.Property<string>("IceRaw")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("PhysicalFactor")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PhysicalRaw")
                                .HasColumnType("TEXT");

                            b1.HasKey("CreatureEntityId");

                            b1.ToTable("Creatures");

                            b1.WithOwner()
                                .HasForeignKey("CreatureEntityId");
                        });

                    b.Navigation("Damage")
                        .IsRequired();
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureLootEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureEntity", "Creature")
                        .WithMany("Loot")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creature");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureMonsterImageLinkEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureEntity", "Creature")
                        .WithOne("MonsterImageLink")
                        .HasForeignKey("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureMonsterImageLinkEntity", "CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Content.MonsterImageAssetEntity", "MonsterImageAsset")
                        .WithMany("CreatureLinks")
                        .HasForeignKey("MonsterImageAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creature");

                    b.Navigation("MonsterImageAsset");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureSoundEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureEntity", "Creature")
                        .WithMany("Sounds")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creature");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.HuntingPlaceCreatureEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureEntity", "Creature")
                        .WithMany("HuntingPlaces")
                        .HasForeignKey("CreatureId");

                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Content.HuntingPlaceEntity", "HuntingPlace")
                        .WithMany("Creatures")
                        .HasForeignKey("HuntingPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creature");

                    b.Navigation("HuntingPlace");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.HuntingPlaceLevelEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Content.HuntingPlaceEntity", "HuntingPlace")
                        .WithMany("LowerLevels")
                        .HasForeignKey("HuntingPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HuntingPlace");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.MonsterImageAliasEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Content.MonsterImageAssetEntity", "MonsterImageAsset")
                        .WithMany("Aliases")
                        .HasForeignKey("MonsterImageAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonsterImageAsset");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.MonsterSpawnCreatureLinkEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureEntity", "Creature")
                        .WithMany("SpawnLinks")
                        .HasForeignKey("CreatureId");

                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Content.MonsterSpawnCoordinateEntity", "Coordinate")
                        .WithMany("CreatureLinks")
                        .HasForeignKey("MonsterSpawnCoordinateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coordinate");

                    b.Navigation("Creature");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntLootEntry", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntSessionEntity", null)
                        .WithMany("LootItems")
                        .HasForeignKey("HuntSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntMonsterEntry", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntSessionEntity", null)
                        .WithMany("KilledMonsters")
                        .HasForeignKey("HuntSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntSessionEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntGroupEntity", "Group")
                        .WithMany("Sessions")
                        .HasForeignKey("HuntGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Character");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntSupplyAdjustment", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntSessionEntity", null)
                        .WithMany("SupplyAdjustments")
                        .HasForeignKey("HuntSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.TeamHuntMemberEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.TeamHuntSessionEntity", "Session")
                        .WithMany("Members")
                        .HasForeignKey("TeamHuntSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.TeamHuntSessionEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Imbuement.CharacterActiveImbuement", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Imbuement.ImbuementProfileEntity", null)
                        .WithMany("ActiveImbuements")
                        .HasForeignKey("ImbuementProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Imbuement.ImbuementProfileEntity", "ImbuementProfile")
                        .WithMany()
                        .HasForeignKey("ImbuementProfileId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Imbuement.ImbuementRecipeEntity", "Recipe")
                        .WithMany()
                        .HasForeignKey("ImbuementRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImbuementProfile");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Imbuement.ImbuementIngredientEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Imbuement.ImbuementRecipeEntity", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("ImbuementRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Content.ItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Imbuement.ImbuementProfileEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Imbuement.UserItemPriceEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.Content.ItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterAccountEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterEntity", "Character")
                        .WithOne("Account")
                        .HasForeignKey("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterAccountEntity", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterAchievementEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterEntity", "Character")
                        .WithMany("Achievements")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterBadgeEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterEntity", "Character")
                        .WithMany("Badges")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterDeathEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterEntity", "Character")
                        .WithMany("Deaths")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterHouseEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterEntity", "Character")
                        .WithMany("Houses")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterSnapshotEntity", b =>
                {
                    b.HasOne("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterEntity", "Character")
                        .WithMany("Snapshots")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.CreatureEntity", b =>
                {
                    b.Navigation("HuntingPlaces");

                    b.Navigation("Loot");

                    b.Navigation("MonsterImageLink");

                    b.Navigation("Sounds");

                    b.Navigation("SpawnLinks");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.HuntingPlaceEntity", b =>
                {
                    b.Navigation("Creatures");

                    b.Navigation("LowerLevels");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.MonsterImageAssetEntity", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("CreatureLinks");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Content.MonsterSpawnCoordinateEntity", b =>
                {
                    b.Navigation("CreatureLinks");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntGroupEntity", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.HuntSessionEntity", b =>
                {
                    b.Navigation("KilledMonsters");

                    b.Navigation("LootItems");

                    b.Navigation("SupplyAdjustments");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Hunts.TeamHuntSessionEntity", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Imbuement.ImbuementProfileEntity", b =>
                {
                    b.Navigation("ActiveImbuements");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.Imbuement.ImbuementRecipeEntity", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("TibiaHuntMaster.Infrastructure.Data.Entities.TibiaData.CharacterEntity", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Achievements");

                    b.Navigation("Badges");

                    b.Navigation("Deaths");

                    b.Navigation("Houses");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
